FROM node:alpine as builder

WORKDIR /usr/src/app
COPY package*.json ./
RUN yarn install
COPY . .
RUN yarn build

FROM nginx:1.15.2-alpine
WORKDIR /var/www
COPY --from=builder /usr/src/app/build/ .
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
