version: '3'

# docker swarm init
# docker stack deploy -c docker-compose.yml appName
# docker stack ps appName
# docker stack rm appName
# docker swarm leave --force

services:
  vmqueue-api:
    image: italosouza/vmqueue-api
    volumes:
      - datacontainer:/usr/src/app/tmp
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 150M
      restart_policy:
        condition: on-failure
    ports:
      - 8080:8000
    env_file:
      - ./backend/.env
    networks:
      - backend
      - frontend

  vmqueue-app:
    image: italosouza/vmqueue-app
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 100M
    ports:
      - 80:80
    depends_on:
      - vmqueue-api
    networks:
      - backend
      - frontend

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "/home/docker/data:/data"
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
    command: redis-server --appendonly yes
    networks:
      - backend

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "9090:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
    networks:
      - backend
      - frontend

networks:
  backend:
  frontend:

volumes:
  datacontainer:
